exports.seed = function (knex, Promise) {
  var tableName = 'brand'

  return knex(tableName).del()
    .then(function () {
      return Promise.all([
        '3T',
        'Absolute Black',
        'Acros',
        'Aerolite',
        'Alligator',
        'Ashima',
        'Avid',
        'Bontrager',
        'Brooks',
        'Campagnolo',
        'Canyon',
        'Cinelli',
        'Chris King',
        'Continental',
        'Control Tech',
        'Cannondale',
        'Easton',
        'Enve',
        'Extralite',
        'Far and Near',
        'Fox',
        'Fulcrum',
        'Gates',
        'Giant',
        'Hutchinson',
        'Kenda',
        'KCNC',
        'KMC',
        'Look',
        'Magura',
        'Mavic',
        'Maxxis',
        'Michelin',
        'Mongoose',
        'Moots',
        'Panaracer',
        'Parlee',
        'Planet X',
        'Praxis',
        'Raleigh',
        'Recon',
        'Reynolds',
        'Ridley',
        'Ritchey',
        'Rockshox',
        'Rohloff',
        'Schwalbe',
        'Shimano',
        'Specialized',
        'Speedplay',
        'SRAM',
        'Sturmey Archer',
        'SunTour',
        'Sugino',
        'THM',
        'Trek',
        'Truvativ',
        'Thomson',
        'Victoria',
        'Vredestein',
        'Wippermann',
        'Wolf Tooth',
        'Xtracycle',
        'Zipp',
      ].map(function (name) {
        return knex(tableName).insert({
          name: name,
        })
      }))
    })
}
